### ISSUE TITLE
How to donate

### ISSUE THREAD

**Issue by wsfive66** [aapeliv/pico-acme#1]
I would like to donate $50 as a token of gratitude, as I am researching how to use API interfaces to store certificates. I have no idea how to solve a great problem by reviewing your code

**Comment by aapeliv** [comment]
Thank you! If you would like to donate as a thank you for this work, please donate to [Let's Encrypt](https://letsencrypt.org/donate/) or to [Couchers.org](https://couchers.org/donate) (this is a non-profit I founded and care deeply about)!

**Comment by wsfive66** [comment]
thanks
